dist: xenial
language: python

cache: pip

branches:
  only:
    - master

matrix:
  include:
    - python: 3.7
      env: NOX_SESSION=check

    - python: 3.6
      env: NOX_SESSION=test-3.6
    - python: 3.7
      env: NOX_SESSION=test-3.7
    - python: 3.8
      env: NOX_SESSION=test-3.8

install:
  - pip install --upgrade nox

script:
  - nox -s ${NOX_SESSION}
